function manPage() {
  const content =
`Usage: makeReact <componentName> -<args>

Naming your components: All component files are generated with start case,
            by default whereas the folder for the component will be lower
            case. Example: modal => Modal

Arguments:  Preceed your arguments with '-'. '--' are ignored. All
            arguments can be placed after one '-' or every argument
            can have it's own '-'.
            Example: -Atn and -A -t -n are both acceptable.

                 ***** FILE GENERATOR ARGUMENTS ******

-S:         Generates a single react component file with out a
            folder. This file by default is going to be a .js
            file with web code in mind.

-A:         Generates all folders and files as .js web files.

-D:         Generates the component as a folder component with
            an index file and the main component file.

-T:         Everything -D does as well as generate a test folder
            along with a test file for you component.

-l:         Will generate all of your files as lowercase instead
            of the default uppercase. Code component names will
            still be generated as uppercase.

-d:         Will generate the component as a folder and will
            generate it with a dataLayer file.

-u:         Will generate the component as a folder and will
            generate it with a utils files. If you pass in -T
            as well it will generate a test file for your utils
            files as well.

-s:         Will generate the component as a folder and will
            generate it with a style file.

                 ***** PLATFORM GENERATOR ARGUMENTS ******

-t:         All files are generated by default as .js files. This
            argument will make them all .ts files for TypeScript
            instead.

-n:         All files are generated by default as react web files
            with HTML code and react web imports. This argument
            will make them all react native files instead with
            react native components and styles.

Common Combinations:

1. makeReact modal -Atn  ~ Generates all component files and folders as
                           react native / TypeScript files.

2. makeReact modal -Du   ~ Generates the component as a react web component
                           inside of a folder with a utils file.

3. makeReact modal -S    ~ Generates a single react web component.
`;
  return content;
}

module.exports = manPage;
